"""Plot catalog for the frontend (form generation).

This is not a strict schema validator; it's a declarative description that your
UI can use to propose controls (column selectors, colors, toggles, etc.).
"""

PLOT_CATALOG: dict = {
    "version": "0.1.0",
    "defaults": {
        "template": "plotly_white",
        "height": 520,
        "width": None,
        "color": "#1f77b4",
        "opacity": 0.85,
    },
    "plot_types": {
        "histogram": {
            "label": "Histogramme",
            "required": ["x"],
            "optional": [
                "nbins",
                "normalize",
                "compare_distributions",
                "stats_lines",
                "log_x",
                "rug",
                "title",
            ],
            "description": "Distribution d'une variable numérique + option de comparaison à des lois connues.",
        },
        "ecdf": {
            "label": "ECDF",
            "required": ["x"],
            "optional": ["stats_lines", "log_x", "title"],
            "description": "Fonction de répartition empirique (utile pour comparer des distributions).",
        },
        "kde": {
            "label": "Densité (KDE)",
            "required": ["x"],
            "optional": ["bandwidth", "compare_distributions", "stats_lines", "log_x", "title"],
            "description": "Estimation de densité par noyau + overlay de lois ajustées (optionnel).",
        },
        "qqplot_normal": {
            "label": "QQ-plot (Normal)",
            "required": ["x"],
            "optional": ["fit_line", "title"],
            "description": "QQ-plot de la variable vs N(0,1) pour évaluer la normalité.",
        },
        "box": {
            "label": "Boîte à moustaches",
            "required": ["y"],
            "optional": ["x", "points", "log_y", "title"],
            "description": "Boxplot (avec groupement optionnel).",
        },
        "violin": {
            "label": "Violon",
            "required": ["y"],
            "optional": ["x", "points", "log_y", "title"],
            "description": "Violin plot (avec groupement optionnel).",
        },
        "scatter": {
            "label": "Nuage de points",
            "required": ["x", "y"],
            "optional": [
                "color_by",
                "trendline",
                "regression",
                "tangent_at",
                "show_stationary_points",
                "show_inflection_points",
                "show_fixed_points",
                "show_gradient",
                "gradient_mode",
                "highlight_extrema",
                "highlight_top_residuals",
                "log_x",
                "log_y",
                "title",
            ],
            "description": "Scatter avec coloration + régression + analyses (tangentes/points critiques).",
        },
        "line": {
            "label": "Courbe",
            "required": ["x", "y"],
            "optional": [
                "color_by",
                "markers",
                "regression",
                "tangent_at",
                "show_stationary_points",
                "show_inflection_points",
                "show_fixed_points",
                "show_gradient",
                "gradient_mode",
                "highlight_extrema",
                "highlight_top_residuals",
                "log_x",
                "log_y",
                "title",
            ],
            "description": "Courbe (x peut être datetime) + régression/analyse optionnelles.",
        },
        "radar": {
            "label": "Radar (Spider)",
            "required": ["group_by", "metrics"],
            "optional": ["agg", "top_n", "normalize", "fill", "colors", "color", "title"],
            "description": "Radar chart multi-métriques par groupe (agrégation + normalisation optionnelle).",
        },
        "parallel_coordinates": {
            "label": "Coordonnées parallèles",
            "required": ["dimensions"],
            "optional": ["color_by", "title"],
            "description": "Visualisation multivariée (dimensions numériques).",
        },
        "scatter_matrix": {
            "label": "Scatter matrix",
            "required": ["dimensions"],
            "optional": ["color_by", "diagonal_visible", "title"],
            "description": "Matrice de nuages de points (pairwise) + diagonale.",
        },
        "density2d_heatmap": {
            "label": "Densité 2D (Heatmap)",
            "required": ["x", "y"],
            "optional": ["nbinsx", "nbinsy", "log_x", "log_y", "title"],
            "description": "Carte de densité 2D (bins) pour gros volumes de points.",
        },
        "density2d_contour": {
            "label": "Densité 2D (Contours)",
            "required": ["x", "y"],
            "optional": ["log_x", "log_y", "title"],
            "description": "Contours de densité 2D (style publication).",
        },
        "bar": {
            "label": "Barres",
            "required": ["x", "y"],
            "optional": ["orientation", "log_y", "title"],
            "description": "Bar chart (catégories vs valeurs).",
        },
        "count": {
            "label": "Comptage catégories",
            "required": ["x"],
            "optional": ["normalize", "top_n", "title"],
            "description": "Count plot (top N optionnel).",
        },
        "corr_heatmap": {
            "label": "Corrélations",
            "required": [],
            "optional": ["method", "title"],
            "description": "Heatmap des corrélations numériques (Pearson/Spearman).",
        },
        "missing_values": {
            "label": "Valeurs manquantes",
            "required": [],
            "optional": ["top_n", "include_zero", "title"],
            "description": "Barres: nombre de valeurs manquantes par colonne (top N).",
        },
        "rolling_mean": {
            "label": "Série temporelle + moyenne mobile",
            "required": ["x", "y"],
            "optional": ["window", "markers", "log_y", "title"],
            "description": "Courbe y=f(x) (x datetime) avec moyenne mobile paramétrable.",
        },
        "stacked_area": {
            "label": "Aires empilées",
            "required": ["x", "y", "group_by"],
            "optional": ["agg", "top_n", "title"],
            "description": "Aires empilées par groupe (agrégation par x et groupe).",
        },
        "cumulative_sum": {
            "label": "Somme cumulée",
            "required": ["x", "y"],
            "optional": ["group_by", "title"],
            "description": "Cumul de y au fil de x (optionnellement par groupe).",
        },
        "heatmap_pivot": {
            "label": "Heatmap (pivot)",
            "required": ["x", "y", "value"],
            "optional": ["agg", "sort_x", "sort_y", "title"],
            "description": "Heatmap à partir d'un pivot (x,y → valeur agrégée).",
        },
        "funnel": {
            "label": "Funnel",
            "required": ["stage", "value"],
            "optional": ["group_by", "agg", "title"],
            "description": "Tunnel de conversion/pipeline (agrégation par étape).",
        },
        "waterfall": {
            "label": "Waterfall",
            "required": ["x", "y"],
            "optional": ["add_total", "title"],
            "description": "Waterfall (deltas) avec total optionnel.",
        },
        "lag_plot": {
            "label": "Lag plot",
            "required": ["y"],
            "optional": ["lag", "title"],
            "description": "Scatter y(t) vs y(t-lag) pour analyser la dépendance temporelle.",
        },
        "acf": {
            "label": "Autocorrélation (ACF)",
            "required": ["y"],
            "optional": ["nlags", "title"],
            "description": "Barres d'autocorrélation (lags) d'une série numérique.",
        },
        "top_words": {
            "label": "Mots fréquents",
            "required": ["text"],
            "optional": ["top_n", "ngram", "stopwords", "min_token_len", "title"],
            "description": "Barres des mots/ngrammes les plus fréquents.",
        },
        "wordcloud": {
            "label": "Nuage de mots",
            "required": ["text"],
            "optional": ["stopwords", "max_words", "title"],
            "description": "Wordcloud rendu en image (dépendance optionnelle 'wordcloud').",
        },
    },
    "known_distributions": ["normal", "lognormal", "exponential", "uniform"],
    "stats_lines": ["mean", "median", "q0.25", "q0.75", "q0.10", "q0.90"],
    "regression": ["linear", "poly2", "poly3"],
    "gradient_mode": ["angle", "slope"],
}
